apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ticketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kushal81/ticketing-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ticketing-config
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: jwt-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ticketing-secrets
                  key: db-password
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ticketing
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
